services:
  - type: web
    name: askus-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
    plan: free
