services:
  - type: web
    name: askus-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_NO_CACHE_DIR
        value: "false"  # hoặc "true" nếu muốn tiết kiệm bộ nhớ khi build
    plan: free
    
